server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.204.131
  rabbitmq:
    host: 192.168.204.131
    port: 5672
    virtual-host: /fengge
    username: fengge
    password: fengge
jwt:
  token:
    pubKeyPath: D:\project-0805\rsa\rsa.pub
    cookieName: gmall-token
    userKey: user-key
    expireTime: 7776000